apiVersion: apps/v1
kind: Deployment
metadata:
  name: grades-tracker-backend
  namespace: grades-tracker-namespace
  labels:
    kind: deployment
    tier: backend
spec:
  replicas: 3

  selector:
    matchLabels:
      tier: backend

  template:
    metadata:
      labels:
        kind: deployment
        tier: backend
    spec:
      containers:
      - name: tracker-backend
        image: karenngugi/grades-tracker-backend:1.0.0
        ports:
        - containerPort: 8000
        env:
        - name: db_host
          valueFrom: 
            configMapKeyRef:
              name: backend-configmap
              key: DB_HOST
        - name: db_port
          valueFrom: 
            configMapKeyRef:
              name: backend-configmap
              key: DB_PORT
        - name: db_name
          valueFrom: 
            configMapKeyRef:
              name: backend-configmap
              key: DB_NAME
        - name: db_user
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: DB_USER
        - name: db_password
          valueFrom:
            secretKeyRef:
              name: db-password
              key: DB_PASSWORD
        - name: api_port
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: API_PORT

