apiVersion: v1
kind: Pod
metadata:
  namespace: test-ns
  name: database-pod
  labels:
    tier: database
    network: backend
spec:
  containers:
  - name: tracker-database
    image: postgres:17
    ports:
    - containerPort: 5432
      name: database-port
    env:
    - name: POSTGRES_USER
      valueFrom:
        configMapKeyRef:
          name: database-configmap
          key: POSTGRES_USER
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-password
          key: POSTGRES_PASSWORD
    - name: POSTGRES_DB
      valueFrom:
        configMapKeyRef:
          name: database-configmap
          key: POSTGRES_DB
    volumeMounts:
    - name: init-db
      mountPath: /docker-entrypoint-initdb.d
  volumes:
  - name: init-db
    configMap:
      name: init-db
