apiVersion: v1
kind: Pod
metadata:
  namespace: test-ns
  name: frontend-pod
  labels:
    tier: frontend
spec:
  containers:
  - name: tracker-frontend
    image: karenngugi/grades-tracker-frontend:1.0.0
    ports:
    - containerPort: 80
      name: frontend-port
