apiVersion: v1
kind: Service
metadata:
  namespace: test-ns
  name: headless-svc
spec:
  selector:
    kind: statefulset
  clusterIP: None
  ports:
  - name: db-headless
    port: 5432
    # targetPort: statefulset-port