apiVersion: v1
kind: PersistentVolume
metadata:
  name: grades-tracker-pv
  labels:
    app: grades-tracker-app
spec:
  claimRef:
    name: grades-tracker-pvc
    namespace: grades-tracker-namespace
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/grades-tracker/postgres
  storageClassName: ""
