apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grades-tracker-pvc
  namespace: grades-tracker-namespace
  labels:
    app: grades-tracker-app
spec:
  selector:
    matchLabels:
      app: grades-tracker-app
  storageClassName: standard
  volumeName: grades-tracker-pv
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  
