apiVersion: v1
kind: Pod
metadata:
  namespace: test-ns
  name: database-pod
  labels:
    tier: database
    network: backend
spec:
  containers:
  - name: tracker-database
    image: postgres:17
    ports:
    - containerPort: 5432
      name: database-port
    env:
    - name: POSTGRES_USER
      valueFrom:
        configMapKeyRef:
          name: database-configmap
          key: POSTGRES_USER
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-password
          key: POSTGRES_PASSWORD
    - name: POSTGRES_DB
      valueFrom:
        configMapKeyRef:
          name: database-configmap
          key: POSTGRES_DB
    volumeMounts:
    - name: init-db
      mountPath: /docker-entrypoint-initdb.d
  volumes:
  - name: init-db
    configMap:
      name: init-db

---

apiVersion: v1
kind: Pod
metadata:
  namespace: test-ns
  name: backend-pod
  labels:
    network: backend
    tier: backend
spec:
  containers:
  - name: tracker-backend
    image: karenngugi/grades-tracker-backend:1.0.0
    ports:
    - containerPort: 3000
      name: backend-port
    env:
    - name: DB_HOST
      valueFrom: 
        configMapKeyRef:
          name: backend-configmap
          key: DB_HOST
    - name: DB_PORT
      valueFrom: 
        configMapKeyRef:
          name: backend-configmap
          key: DB_PORT
    - name: DB_NAME
      valueFrom: 
        configMapKeyRef:
          name: backend-configmap
          key: DB_NAME
    - name: DB_USER
      valueFrom:
        configMapKeyRef:
          name: backend-configmap
          key: DB_USER
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-password
          key: DB_PASSWORD
    - name: API_PORT
      valueFrom:
        configMapKeyRef:
          name: backend-configmap
          key: API_PORT

---

apiVersion: v1
kind: Pod
metadata:
  namespace: test-ns
  name: frontend-pod
  labels:
    tier: frontend
spec:
  containers:
  - name: tracker-frontend
    image: karenngugi/grades-tracker-frontend:1.0.0
    ports:
    - containerPort: 80
      name: frontend-port
