apiVersion: v1
kind: Service
metadata:
  namespace: test-ns
  name: database-svc
spec:
  selector:
    tier: database
  ports:
  - name: database-service
    protocol: TCP
    port: 5432
    targetPort: database-port
