apiVersion: v1
kind: Service
metadata:
  namespace: grades-tracker-namespace
  name: database-svc
  labels:
    tier: database
spec:
  selector:
    tier: database
  ports:
  - name: database-service
    protocol: TCP
    port: 5432
    targetPort: database-port
