apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
  # name: grades-tracker-pv
  labels:
    app: test-app
    # app: grades-tracker-app
spec:
  claimRef:
    name: test-pvc
    # name: grades-tracker-pvc
    namespace: test-ns
    # namespace: grades-tracker-namespace
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/test/postgres
    # path: /data/grades-tracker/postgres
  storageClassName: ""

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  # name: grades-tracker-pvc
  namespace: test-ns
  # namespace: grades-tracker-namespace
  labels:
    app: test-app
    # app: grades-tracker-app
    tier: database
spec:
  selector:
    matchLabels:
      app: test-app
      # app: grades-tracker-app
      tier: database
  storageClassName: ""
  volumeName: test-pv
  # volumeName: grades-tracker-pv
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  
