apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: grades-tracker-replicaset
  namespace: grades-tracker-namespace
  labels:
    tier: backend
spec:
  replicas: 2

  selector:
    matchLabels:
      tier: backend

  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
      - name: tracker-backend
        image: karenngugi/grades-tracker-backend:1.0.0
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          valueFrom: 
            configMapKeyRef:
              name: backend-configmap
              key: DB_HOST
        - name: DB_PORT
          valueFrom: 
            configMapKeyRef:
              name: backend-configmap
              key: DB_PORT
        - name: DB_NAME
          valueFrom: 
            configMapKeyRef:
              name: backend-configmap
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password
              key: DB_PASSWORD
        - name: API_PORT
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: API_PORT

